spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      # 基本属性
      url: jdbc:mysql://localhost:3306/chapter25_4?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
  jpa:
    # 显示 sql
    show-sql: true
    # 数据库类型
    database: mysql
    # JPA 配置
    hibernate:
      ddl-auto: update
    # 指定生成的表的引擎为InnoDB类型（默认是MyISAM，MyISAM不支持事务）
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  data:
    mongodb:
      # 默认uri`mongodb://localhost:27017/test`
      # 数据库有用户名和密码可参考：mongodb://name:password@localhost:27017/db
      uri: mongodb://localhost:27017/test
