server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关配置
    druid:
      # 监控统计拦截的 filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      # 基本属性 	allowMultiQueries：设置为true后，数据库那边才允许你批量更新
      url: jdbc:mysql://localhost:3306/chapter9?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true 	#编码属性设置了存储数据到数据库才不会是乱码
      username: root
      password: 123456
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并指定每个连接上 PSCache 的大小。oracle 设为 true，mysql 设为 false。分库分表较多推荐设置为 false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 注意：一定要对应 mapper 映射xml文件的所在路径
  type-aliases-package: com.example.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 可以自控制台上输出 sql 语句

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 通用Mapper
mapper:
  # 主键自增回写方法,默认值MYSQL,详细说明请看文档
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  # 设置 insert 和 update 中，是否判断字符串类型!=''
  not-empty: true
  # 枚举按简单类型处理
  enum-as-simple-type: true
